display:
  default:
    display_title: الافتراضي
    display_options:
      fields:
        operations:
          label: العمليات
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
