display:
  default:
    display_title: الافتراضي
    display_options:
      fields:
        media_bulk_form:
          action_title: إجراء
        bundle:
          label: النوع
        status:
          label: الحالة
          settings:
            format_custom_true: منشور
        operations:
          label: العمليات
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      filters:
        bundle:
          expose:
            label: النوع
        status:
          group_info:
            group_items:
              1:
                title: منشور
        langcode:
          expose:
            label: اللغة
