display:
  default:
    display_title: الافتراضي
    display_options:
      fields:
        filename:
          label: الاسم
        status:
          label: الحالة
        operations:
          label: العمليات
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      filters:
        status:
          expose:
            label: الحالة
  page_2:
    display_options:
      fields:
        type:
          label: 'نوع الكيان'
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
