display:
  default:
    display_options:
      fields:
        state:
          label: الحالة
        label:
          label: التسمية
        translator:
          label: المزود
        changed:
          label: 'تم التغير'
        operations:
          label: العمليات
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      filters:
        state:
          expose:
            label: الحالة
        source_language:
          expose:
            label: 'لغة المصدر'
        translator:
          expose:
            label: المزود
