display:
  default:
    display_options:
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      fields:
        state:
          label: الحالة
        label:
          label: التسمية
        type:
          label: النوع
        changed:
          label: 'تم التغير'
        operations:
          label: العمليات
  checkout:
    display_title: الأداء
    display_options:
      fields:
        label:
          label: التسمية
        type:
          label: النوع
        changed:
          label: 'تم التغير'
