field.formatter.settings.lite_youtube_embed:
  type: mapping
  label: 'Lite YouTube embed (with OEmbed fallback) formatter settings'
  mapping:
    max_width:
      type: integer
      label: 'Maximum width'
    max_height:
      type: integer
      label: 'Maximum height'
