_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 0b0187d0-fb98-484e-8cb1-2faf3c6640c5
name: 'Sultan Qaboos University'
mail: admin@example.com
slogan: 'جامعة السلطان قابوس'
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
